name: Microservices CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build catalogue-service
        run: |
          cd catalogue-service
          mvn -B clean install

      - name: Build commande-service
        run: |
          cd commande-service
          mvn -B clean install

      - name: Build config-service
        run: |
          cd config-service
          mvn -B clean install

      - name: Build discovery-service
        run: |
          cd discovery-service
          mvn -B clean install

      - name: Build gateway-service
        run: |
          cd gateway-service
          mvn -B clean install

      - name: Build paiement-service
        run: |
          cd paiement-service
          mvn -B clean install